CREATE TABLE order_tickets (
    id bigint primary key,
    credentials varchar not null
);

CREATE TABLE orders (
    id bigint primary key generated by default as identity,
    credentials varchar not null,
    sum int not null,
    status varchar,
    order_ticket_id bigint references order_tickets(id)
);