global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'status_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['status-service:8080']
        labels:
          application: 'Status Service Application'
  - job_name: 'order_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8080']
        labels:
          application: 'Order Service Application'
  - job_name: 'ticket_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ticket-service:8080']
        labels:
          application: 'Ticket Service Application'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8080']
        labels:
          application: 'Notification Service Application'