CREATE TABLE routes (
    id bigint primary key generated by default as identity ,
    departure_time timestamp,
    place_from varchar,
    place_to varchar,
    price int
);

CREATE TABLE free_tickets (
    id bigint primary key generated by default as identity,
    route_id bigint not null references routes(id)
);

CREATE TABLE booked_tickets (
    id bigint primary key,
    credentials varchar not null,
    order_status varchar not null,
    route_id bigint not null references routes(id)
);

insert into routes(departure_time, place_from, place_to, price) VALUES ('2023-03-02', 'Dnipro', 'Lviv', 200);

insert into free_tickets(route_id) values (1);
insert into free_tickets(route_id) values (1);
insert into free_tickets(route_id) values (1);
insert into free_tickets(route_id) values (1);
insert into free_tickets(route_id) values (1);

insert into routes(departure_time, place_from, place_to, price) VALUES ('2023-07-12', 'Kyiv', 'Kharkiv', 300);

insert into free_tickets(route_id) values (2);
insert into free_tickets(route_id) values (2);
insert into free_tickets(route_id) values (2);
insert into free_tickets(route_id) values (2);