server:
  port: 8083

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: 1111
  application:
    name: order-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  rabbitmq:
    port: 5672
    host: localhost
    username: user
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      status:
        sliding-window-size: 5
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true


