server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres-order:5430/orders_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111
  rabbitmq:
    port: 5672
    host: myRabbitMQ
    username: user
    password: password
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  flyway:
    url: jdbc:postgresql://postgres-order:5430/orders_db
    user: postgres
    password: 1111
    baselineOnMigrate: true
    group: true
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

resilience4j:
  circuitbreaker:
    instances:
      status:
        sliding-window-size: 5
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
