eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: status
          uri: lb://status-service
          predicates:
            - Path=/status
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order
        - id: route
          uri: lb://ticket-service
          predicates:
            - Path=/routes/**
        - id: ticket
          uri: lb://ticket-service
          predicates:
            - Path=/tickets/**