server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://postgres-ticket:5431/tickets_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111
  flyway:
    url: jdbc:postgresql://postgres-ticket:5431/tickets_db
    user: postgres
    password: 1111
    baselineOnMigrate: true
    group: true
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
